version: '3.9'

services:
  app:
    build:
      context: .
# cmd/chat/main.go実行時のみ
#    env_file:
#      - .env
#    ports:
#      - 8080:8080
    container_name: go-app
    volumes:
      - ./:/go/src/app