name: test and lint code

on: push

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: github.com/mi11km/playground
  SLACK_CHANNEL: github-actions通知
  SLACK_ICON_EMOJI: ':golang:'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install Dependencies
        run: go mod download
      - name: Test
        run: go test -v ./...
      - name: Lint
        run: go vet ./...

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: Test Success
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger